spring.application.name=file-upload

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

file.upload.directory=uploads
file.upload.max-size-bytes=2097152
file.upload.allowed-types=image/png,image/jpeg,application/pdf
